import React, { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { BookOpen, Check, FileDown, Save, Send, Sparkles } from 'lucide-react-native';
import { colors, commonStyles } from '../../shared/theme';

export default function AiGeneratorScreen() {
  const [topic, setTopic] = useState('Hình học lớp 10 - Thể tích khối đa diện');
  const [count, setCount] = useState('10');
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [error, setError] = useState('');
  const canGenerate = topic.trim().length >= 4 && Number(count) >= 1 && Number(count) <= 50;
  async function generate() {
    if (!canGenerate) { setError('Nhập chủ đề tối thiểu 4 ký tự và số câu từ 1 đến 50.'); return; }
    setError(''); setLoading(true); setGenerated(false);
    await new Promise((resolve) => setTimeout(resolve, 900));
    setLoading(false); setGenerated(true);
  }
  return <ScrollView style={commonStyles.screen} contentContainerStyle={commonStyles.content}><Text style={commonStyles.eyebrow}>AI Assistant</Text><Text style={[commonStyles.title, { marginTop: 7 }]}>Soạn bài nhanh hơn.</Text><Text style={[commonStyles.muted, { marginTop: 8 }]}>Tạo quiz hoặc outline bài giảng để bắt đầu, rồi chỉnh sửa theo lớp của bạn.</Text><View style={styles.form}><View style={styles.formTitle}><Sparkles color={colors.coral} size={18} /><Text style={styles.formHeading}>Tạo quiz 10 câu</Text></View><Text style={styles.label}>Chủ đề</Text><TextInput value={topic} onChangeText={setTopic} style={styles.input} placeholder="Ví dụ: Hệ phương trình lớp 9" /><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.label}>Cấp độ</Text><View style={styles.select}><Text style={styles.selectText}>Lớp 10</Text><BookOpen size={15} color={colors.muted} /></View></View><View style={{ flex: 1 }}><Text style={styles.label}>Số câu</Text><TextInput value={count} onChangeText={setCount} keyboardType="number-pad" style={styles.input} /></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={generate} style={[styles.generate, !canGenerate && styles.disabled]}>{loading ? <ActivityIndicator color={colors.ink} /> : <><Sparkles size={17} color={colors.ink} /><Text style={styles.generateText}>Bắt đầu tạo</Text></>}</Pressable></View>{loading && <View style={styles.loading}><ActivityIndicator color={colors.coral} /><Text style={styles.loadingTitle}>AI đang soạn câu hỏi...</Text><Text style={commonStyles.muted}>Thường mất khoảng 30 giây</Text></View>}{generated && !loading && <View style={styles.result}><View style={styles.resultHeader}><View><Text style={commonStyles.eyebrow}>Đã hoàn thành</Text><Text style={styles.resultTitle}>Thể tích khối đa diện</Text></View><Text style={styles.badge}>{count} CÂU</Text></View><View style={styles.question}><Text style={styles.questionNumber}>01</Text><View style={{ flex: 1 }}><Text style={styles.questionText}>Cho khối chóp có diện tích đáy và chiều cao đã biết, thể tích là?</Text><Text style={styles.answer}>A · S.h/3</Text></View></View><View style={styles.question}><Text style={styles.questionNumber}>02</Text><View style={{ flex: 1 }}><Text style={styles.questionText}>Mặt phẳng song song với đáy tạo ra hình gì?</Text><Text style={styles.answer}>B · Hình đồng dạng</Text></View></View><View style={styles.resultActions}><Pressable style={styles.action}><FileDown size={16} color={colors.ink} /><Text style={styles.actionText}>Export PDF</Text></Pressable><Pressable style={styles.action}><Save size={16} color={colors.ink} /><Text style={styles.actionText}>Lưu thư viện</Text></Pressable><Pressable style={styles.assign}><Send size={16} color={colors.lime} /><Text style={styles.assignText}>Giao cho lớp</Text></Pressable></View></View>}</ScrollView>;
}
const styles = StyleSheet.create({ form: { backgroundColor: colors.white, borderRadius: 20, marginTop: 26, padding: 18 }, formTitle: { alignItems: 'center', flexDirection: 'row' }, formHeading: { color: colors.ink, fontSize: 17, fontWeight: '800', marginLeft: 8 }, label: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: .7, marginBottom: 6, marginTop: 18, textTransform: 'uppercase' }, input: { borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 14, paddingHorizontal: 12, paddingVertical: 11 }, row: { flexDirection: 'row', gap: 12 }, select: { alignItems: 'center', borderColor: colors.line, borderRadius: 12, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 12 }, selectText: { color: colors.ink, fontSize: 14 }, error: { color: colors.danger, fontSize: 12, marginTop: 12 }, generate: { alignItems: 'center', backgroundColor: colors.lime, borderRadius: 99, flexDirection: 'row', justifyContent: 'center', marginTop: 22, padding: 14 }, disabled: { opacity: .45 }, generateText: { color: colors.ink, fontSize: 13, fontWeight: '800', marginLeft: 7 }, loading: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: 20, marginTop: 14, padding: 25 }, loadingTitle: { color: colors.ink, fontSize: 15, fontWeight: '800', marginTop: 11, marginBottom: 4 }, result: { backgroundColor: colors.ink, borderRadius: 20, marginTop: 14, padding: 18 }, resultHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' }, resultTitle: { color: colors.paper, fontSize: 19, fontWeight: '800', marginTop: 5 }, badge: { backgroundColor: colors.lime, borderRadius: 8, color: colors.ink, fontSize: 9, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 6 }, question: { borderTopColor: '#2C494B', borderTopWidth: 1, flexDirection: 'row', gap: 12, marginTop: 20, paddingTop: 16 }, questionNumber: { color: colors.lime, fontFamily: 'monospace', fontSize: 11, fontWeight: '800' }, questionText: { color: colors.paper, fontSize: 13, fontWeight: '700', lineHeight: 20 }, answer: { color: colors.sky, fontSize: 11, marginTop: 7 }, resultActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 22 }, action: { alignItems: 'center', backgroundColor: colors.paper, borderRadius: 99, flexDirection: 'row', paddingHorizontal: 11, paddingVertical: 10 }, actionText: { color: colors.ink, fontSize: 10, fontWeight: '800', marginLeft: 5 }, assign: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 99, flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 10 }, assignText: { color: colors.ink, fontSize: 10, fontWeight: '800', marginLeft: 5 } });
