import React, { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BarChart3, Square } from 'lucide-react-native';
import { LiveClassSocketClient } from '../../core/realtime/live-class-socket.client';
import { colors, commonStyles } from '../../shared/theme';

export default function LiveQuizTeacherScreen({ sessionId, classId, quizId, token }: { sessionId: string; classId: string; quizId: string; token: string }) {
  const client = useRef(new LiveClassSocketClient()).current; const [count, setCount] = useState(0); const [leaderboard, setLeaderboard] = useState<Array<{ studentId: string; score: number }>>([]);
  useEffect(() => { client.connect(process.env.EXPO_PUBLIC_LIVE_URL ?? 'http://localhost:3000', token); void client.joinSession({ sessionId, classId }); const stopPresence = client.onPresence((event) => setCount(event.connectedStudentCount)); const stopLeaderboard = client.onLeaderboard((event) => setLeaderboard(event.leaderboard)); return () => { stopPresence(); stopLeaderboard(); client.disconnect(); }; }, [classId, client, sessionId, token]);
  return <View style={[commonStyles.screen, styles.screen]}><Text style={commonStyles.eyebrow}>Live classroom</Text><Text style={commonStyles.title}>Quiz đang diễn ra</Text><Text style={commonStyles.muted}>{count} học sinh đang kết nối</Text><View style={styles.chart}>{[0, 1, 2, 3].map((option) => <View key={option} style={styles.barColumn}><View style={[styles.bar, { height: 28 + (leaderboard.length * (option + 1) % 80) }]} /><Text style={styles.barLabel}>{String.fromCharCode(65 + option)}</Text></View>)}</View><Pressable onPress={() => void client.nextQuestion({ sessionId, quizId, questionIndex: 0 })} style={styles.next}><BarChart3 color={colors.ink} size={18} /><Text style={styles.nextText}>Mở câu hỏi</Text></Pressable><Pressable onPress={() => void client.endSession(sessionId)} style={styles.end}><Square color={colors.white} size={16} /><Text style={styles.endText}>Kết thúc session</Text></Pressable></View>;
}

const styles = StyleSheet.create({ screen: { padding: 22 }, chart: { alignItems: 'flex-end', backgroundColor: colors.white, borderRadius: 18, flexDirection: 'row', height: 190, justifyContent: 'space-around', marginTop: 24, padding: 20 }, barColumn: { alignItems: 'center', justifyContent: 'flex-end' }, bar: { backgroundColor: colors.coral, borderRadius: 8, width: 38 }, barLabel: { color: colors.muted, fontWeight: '900', marginTop: 8 }, next: { alignItems: 'center', backgroundColor: colors.lime, borderRadius: 99, flexDirection: 'row', justifyContent: 'center', marginTop: 20, padding: 14 }, nextText: { color: colors.ink, fontWeight: '900', marginLeft: 8 }, end: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 99, flexDirection: 'row', justifyContent: 'center', marginTop: 10, padding: 14 }, endText: { color: colors.white, fontWeight: '800', marginLeft: 8 } });