import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ChevronRight, Plus, Sparkles, Users } from 'lucide-react-native';
import { ModeSwitcher } from '../../shared/components/ModeSwitcher';
import { colors, commonStyles } from '../../shared/theme';

const classes = [{ name: 'Toán 10A', subject: 'Toán học', students: 32, code: 'MATH10' }, { name: 'Luyện thi 12', subject: 'Ôn thi THPT', students: 18, code: 'THPT12' }];

export default function TeacherDashboardScreen({ navigation }: { navigation: { navigate: (screen: string) => void } }) {
  return <ScrollView style={commonStyles.screen} contentContainerStyle={commonStyles.content}><Text style={commonStyles.eyebrow}>Teacher Mode</Text><View style={styles.top}><View><Text style={[commonStyles.title, { marginTop: 6 }]}>Lớp của bạn</Text><Text style={commonStyles.muted}>Thứ ba, 12 tháng 9</Text></View><Text style={styles.avatar}>N</Text></View><ModeSwitcher /><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Đang quản lý</Text><Pressable style={styles.add}><Plus size={16} color={colors.ink} /><Text style={styles.addText}>Tạo lớp</Text></Pressable></View>{classes.map((item) => <Pressable key={item.code} style={commonStyles.card}><View style={styles.classRow}><View style={styles.classIcon}><Users color={colors.lime} size={20} /></View><View style={{ flex: 1 }}><Text style={styles.className}>{item.name}</Text><Text style={commonStyles.muted}>{item.subject} · {item.students} học sinh</Text></View><ChevronRight size={18} color={colors.muted} /></View><View style={styles.codeRow}><Text style={styles.codeLabel}>MÃ THAM GIA</Text><Text style={styles.code}>{item.code}</Text></View></Pressable>)}<Pressable onPress={() => navigation.navigate('AI')} style={styles.aiCard}><View style={styles.aiTop}><View style={styles.aiIcon}><Sparkles color={colors.ink} size={18} /></View><Text style={styles.aiLabel}>TRỢ LÝ AI</Text></View><Text style={styles.aiTitle}>Soạn bài tiếp theo trong 30 giây.</Text><Text style={styles.aiAction}>Tạo quiz hoặc giáo án <ChevronRight size={15} color={colors.ink} /></Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ top: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 22, marginTop: 8 }, avatar: { backgroundColor: colors.lime, borderRadius: 20, color: colors.ink, fontSize: 18, fontWeight: '800', padding: 11 }, sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14, marginTop: 30 }, sectionTitle: { color: colors.ink, fontSize: 22, fontWeight: '800' }, add: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 99, flexDirection: 'row', paddingHorizontal: 13, paddingVertical: 9 }, addText: { color: colors.lime, fontSize: 11, fontWeight: '800', marginLeft: 5 }, classRow: { alignItems: 'center', flexDirection: 'row' }, classIcon: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 13, height: 42, justifyContent: 'center', marginRight: 12, width: 42 }, className: { color: colors.ink, fontSize: 16, fontWeight: '800', marginBottom: 3 }, codeRow: { borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, paddingTop: 13 }, codeLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1 }, code: { color: colors.coral, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, aiCard: { backgroundColor: colors.coral, borderRadius: 18, marginTop: 14, padding: 18 }, aiTop: { alignItems: 'center', flexDirection: 'row' }, aiIcon: { alignItems: 'center', backgroundColor: colors.lime, borderRadius: 11, height: 34, justifyContent: 'center', width: 34 }, aiLabel: { color: colors.ink, fontSize: 10, fontWeight: '900', letterSpacing: 1, marginLeft: 9 }, aiTitle: { color: colors.ink, fontSize: 21, fontWeight: '900', marginTop: 30, maxWidth: 260 }, aiAction: { alignItems: 'center', color: colors.ink, flexDirection: 'row', fontSize: 12, fontWeight: '800', marginTop: 17 } });
