import React, { useEffect, useRef, useState } from 'react';
import { Animated, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Award, Flame, Gift, Lock, Sparkles } from 'lucide-react-native';
import { colors } from '../theme';
import { DailyQuest, GamificationProfile } from '../../core/api/classsync-api';

export function CSStreakHeaderWidget({ profile }: { profile: GamificationProfile }) {
  const pulse = useRef(new Animated.Value(1)).current;
  useEffect(() => { Animated.loop(Animated.sequence([Animated.timing(pulse, { toValue: 1.08, duration: 700, useNativeDriver: true }), Animated.timing(pulse, { toValue: 1, duration: 700, useNativeDriver: true })])).start(); }, [pulse]);
  const progress = Math.min(1, profile.currentXP / (100 * (profile.level + 1) ** 1.5));
  return <View style={styles.streak}><View style={styles.streakTop}><Animated.View style={{ transform: [{ scale: pulse }] }}><Flame color={colors.coral} fill={colors.coral} size={30} /></Animated.View><View style={styles.streakCopy}><Text style={styles.label}>Chuỗi học tập</Text><Text style={styles.streakValue}>{profile.currentStreakDays} ngày liên tiếp</Text></View><Text style={styles.level}>LV {profile.level}</Text></View><View style={styles.track}><View style={[styles.progress, { width: `${progress * 100}%` }]} /></View><Text style={styles.subtle}>{profile.currentXP} XP · còn {profile.streakFreezeTokens} lượt bảo vệ chuỗi</Text></View>;
}

export function CSQuestCardWidget({ quest, onClaim }: { quest: DailyQuest; onClaim: () => void }) {
  const [celebrating, setCelebrating] = useState(false);
  const claim = () => { setCelebrating(true); onClaim(); setTimeout(() => setCelebrating(false), 900); };
  const progress = Math.min(1, quest.currentCount / quest.targetCount);
  return <View style={styles.quest}><View style={styles.questIcon}><Gift color={colors.ink} size={21} /></View><View style={styles.questBody}><Text style={styles.questTitle}>{quest.questType === 'COMPLETE_3_DEADLINES' ? 'Hoàn thành 3 deadline' : quest.questType === 'SCAN_1_OCR_ASSIGNMENT' ? 'Quét 1 bài tập bằng OCR' : 'Ôn lại chủ đề yếu'}</Text><Text style={styles.subtle}>{quest.currentCount}/{quest.targetCount} · +{quest.xpReward} XP · +{quest.coinReward} coin</Text><View style={styles.track}><View style={[styles.progress, { width: `${progress * 100}%`, backgroundColor: colors.coral }]} /></View></View>{quest.status === 'COMPLETED' ? <Pressable accessibilityRole="button" onPress={claim} style={styles.claim}><Text style={styles.claimText}>Nhận</Text></Pressable> : null}{celebrating && <View pointerEvents="none" style={styles.confetti}>{[0, 1, 2, 3, 4].map((item) => <Sparkles key={item} color={item % 2 ? colors.coral : colors.lime} size={14} style={{ left: item * 19 }} />)}</View>}</View>;
}

export function CSBadgeShowcaseGrid({ badges, locked = [], onLockedPress }: { badges: Array<{ code: string; title: string; description?: string }>; locked?: Array<{ code: string; title: string; condition: string }>; onLockedPress?: (badge: { code: string; title: string; condition: string }) => void }) {
  const [selected, setSelected] = useState<{ title: string; condition: string }>();
  return <><View style={styles.grid}>{badges.map((badge) => <View style={[styles.badge, styles.earned]} key={badge.code}><Award color={colors.yellow} fill={colors.yellow} size={25} /><Text style={styles.badgeTitle}>{badge.title}</Text></View>)}{locked.map((badge) => <Pressable key={badge.code} onPress={() => { setSelected(badge); onLockedPress?.(badge); }} style={[styles.badge, styles.locked]}><Lock color={colors.muted} size={22} /><Text style={[styles.badgeTitle, { color: colors.muted }]}>{badge.title}</Text></Pressable>)}</View><Modal transparent visible={Boolean(selected)} onRequestClose={() => setSelected(undefined)}><Pressable style={styles.modalBackdrop} onPress={() => setSelected(undefined)}><View style={styles.dialog}><Text style={styles.dialogTitle}>{selected?.title}</Text><Text style={styles.subtle}>{selected?.condition}</Text></View></Pressable></Modal></>;
}

const styles = StyleSheet.create({ streak: { backgroundColor: colors.ink, borderRadius: 20, padding: 17 }, streakTop: { alignItems: 'center', flexDirection: 'row' }, streakCopy: { flex: 1, marginLeft: 12 }, label: { color: colors.sky, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, streakValue: { color: colors.white, fontSize: 18, fontWeight: '800', marginTop: 3 }, level: { color: colors.lime, fontSize: 13, fontWeight: '900' }, track: { backgroundColor: 'rgba(255,255,255,.18)', borderRadius: 8, height: 7, marginTop: 13, overflow: 'hidden' }, progress: { backgroundColor: colors.lime, borderRadius: 8, height: '100%' }, subtle: { color: colors.muted, fontSize: 11, marginTop: 7 }, quest: { alignItems: 'center', backgroundColor: colors.white, borderRadius: 18, flexDirection: 'row', marginTop: 12, padding: 14, position: 'relative' }, questIcon: { alignItems: 'center', backgroundColor: colors.lime, borderRadius: 12, height: 40, justifyContent: 'center', width: 40 }, questBody: { flex: 1, marginLeft: 11 }, questTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' }, claim: { backgroundColor: colors.coral, borderRadius: 99, paddingHorizontal: 12, paddingVertical: 9 }, claimText: { color: colors.ink, fontSize: 11, fontWeight: '900' }, confetti: { flexDirection: 'row', position: 'absolute', right: 12, top: -8 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 10 }, badge: { alignItems: 'center', borderRadius: 14, justifyContent: 'center', minHeight: 90, padding: 10, width: '30%' }, earned: { backgroundColor: '#FFF5D6', borderColor: colors.yellow, borderWidth: 1 }, locked: { backgroundColor: colors.line }, badgeTitle: { color: colors.ink, fontSize: 10, fontWeight: '800', marginTop: 8, textAlign: 'center' }, modalBackdrop: { alignItems: 'center', backgroundColor: 'rgba(16,39,42,.45)', flex: 1, justifyContent: 'center', padding: 24 }, dialog: { backgroundColor: colors.white, borderRadius: 18, padding: 22, width: '100%' }, dialogTitle: { color: colors.ink, fontSize: 20, fontWeight: '800' } });