import React, { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, Vibration, View } from 'react-native';
import { Zap } from 'lucide-react-native';
import { LiveClassSocketClient, LeaderboardEntry } from '../../core/realtime/live-class-socket.client';
import { colors, commonStyles } from '../../shared/theme';

export default function LiveQuizBattleScreen({ sessionId, classId, token, options = ['A', 'B', 'C', 'D'] }: { sessionId: string; classId: string; token: string; options?: string[] }) {
  const client = useRef(new LiveClassSocketClient()).current; const started = useRef(Date.now()).current; const [leaderboard, setLeaderboard] = useState<LeaderboardEntry[]>([]); const [selected, setSelected] = useState<number>();
  useEffect(() => { client.connect(process.env.EXPO_PUBLIC_LIVE_URL ?? 'http://localhost:3000', token); void client.joinSession({ sessionId, classId }); const stop = client.onLeaderboard((event) => setLeaderboard(event.leaderboard)); return () => { stop(); client.disconnect(); }; }, [classId, client, sessionId, token]);
  async function answer(optionIndex: number) { if (selected != null) return; setSelected(optionIndex); Vibration.vibrate(35); await client.submitAnswer({ sessionId, questionIndex: 0, optionIndex, responseTimeMs: Date.now() - started, correct: optionIndex === 0, timeLimitMs: 30_000 }); }
  return <View style={[commonStyles.screen, styles.screen]}><View style={styles.header}><View><Text style={commonStyles.eyebrow}>Quiz battle</Text><Text style={styles.title}>Chọn thật nhanh</Text></View><Zap color={colors.lime} fill={colors.lime} size={28} /></View><View style={styles.grid}>{options.map((option, index) => <Pressable key={option} disabled={selected != null} onPress={() => void answer(index)} style={[styles.option, { backgroundColor: [colors.coral, colors.sky, colors.lime, colors.yellow][index % 4] }, selected === index && styles.selected]}><Text style={styles.optionText}>{option}</Text></Pressable>)}</View><Text style={styles.rankTitle}>Bảng xếp hạng trực tiếp</Text>{leaderboard.slice(0, 5).map((entry, index) => <View key={entry.studentId} style={styles.rank}><Text style={styles.rankNumber}>{index + 1}</Text><Text style={styles.rankName}>{entry.studentId}</Text><Text style={styles.rankScore}>{entry.score} điểm</Text></View>)}</View>;
}

const styles = StyleSheet.create({ screen: { padding: 20 }, header: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 20, flexDirection: 'row', justifyContent: 'space-between', padding: 18 }, title: { color: colors.white, fontSize: 25, fontWeight: '900', marginTop: 5 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 22 }, option: { alignItems: 'center', borderRadius: 18, height: 125, justifyContent: 'center', width: '47%' }, selected: { borderColor: colors.ink, borderWidth: 4 }, optionText: { color: colors.ink, fontSize: 34, fontWeight: '900' }, rankTitle: { color: colors.ink, fontSize: 19, fontWeight: '900', marginTop: 28 }, rank: { alignItems: 'center', backgroundColor: colors.white, borderRadius: 12, flexDirection: 'row', marginTop: 8, padding: 12 }, rankNumber: { color: colors.coral, fontSize: 17, fontWeight: '900', width: 28 }, rankName: { color: colors.ink, flex: 1, fontWeight: '700' }, rankScore: { color: colors.muted, fontSize: 12, fontWeight: '800' } });