import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Camera, CheckCircle2, Clock3, ScanLine } from 'lucide-react-native';
import { ModeSwitcher } from '../../shared/components/ModeSwitcher';
import { colors, commonStyles } from '../../shared/theme';
import { CSBadgeShowcaseGrid, CSQuestCardWidget, CSStreakHeaderWidget } from '../../shared/components/gamification';
import { DailyQuest, GamificationProfile } from '../../core/api/classsync-api';

const items = [
  { time: '08:00', title: 'Toán học', meta: 'Phòng A203 · Cô Hương', color: colors.lime, status: 'Đang học' },
  { time: '14:30', title: 'Vật lý', meta: 'Phòng Lab 02 · Thầy Nam', color: colors.sky, status: 'Sắp tới' },
];

const initialGamificationProfile: GamificationProfile = { userId: 'current-user', currentXP: 340, level: 2, currentStreakDays: 8, longestStreakDays: 12, coinsBalance: 120, streakFreezeTokens: 1, unlockedBadges: ['EARLY_BIRD'], inventoryItems: ['STREAK_FREEZE'] };
const initialQuest: DailyQuest = { id: 'daily-1', questType: 'COMPLETE_3_DEADLINES', targetCount: 3, currentCount: 2, xpReward: 80, coinReward: 20, expiresAt: new Date().toISOString(), status: 'IN_PROGRESS' };

export default function StudentDashboardScreen({ navigation }: { navigation: { navigate: (screen: string) => void } }) {
  const [profile, setProfile] = useState(initialGamificationProfile);
  const [quest, setQuest] = useState(initialQuest);
  return <ScrollView style={commonStyles.screen} contentContainerStyle={commonStyles.content}><View style={styles.header}><View><Text style={commonStyles.eyebrow}>Thứ ba, 12 tháng 9</Text><Text style={[commonStyles.title, styles.greeting]}>Xin chào, An.</Text></View><Text style={styles.avatar}>A</Text></View><ModeSwitcher /><CSStreakHeaderWidget profile={profile} /><CSQuestCardWidget quest={quest} onClaim={() => { setQuest({ ...quest, status: 'CLAIMED' }); setProfile({ ...profile, currentXP: profile.currentXP + quest.xpReward, coinsBalance: profile.coinsBalance + quest.coinReward }); }} /><Text style={styles.sectionTitle}>Huy hiệu của bạn</Text><CSBadgeShowcaseGrid badges={[{ code: 'EARLY_BIRD', title: 'Dậy sớm' }]} locked={[{ code: 'NIGHT_OWL', title: 'Cú đêm', condition: 'Hoàn thành 5 phiên học sau 20:00' }, { code: 'WEEKEND_WARRIOR', title: 'Chiến binh cuối tuần', condition: 'Học tập trong 4 cuối tuần' }]} /><View style={styles.titleRow}><View><Text style={styles.sectionTitle}>Lịch hôm nay</Text><Text style={commonStyles.muted}>Bạn có 3 việc cần xử lý</Text></View><Clock3 color={colors.coral} size={24} /></View>{items.map((item) => <View style={commonStyles.card} key={item.title}><View style={styles.event}><Text style={styles.time}>{item.time}</Text><View style={[styles.marker, { backgroundColor: item.color }]} /><View style={styles.eventCopy}><Text style={styles.eventTitle}>{item.title}</Text><Text style={commonStyles.muted}>{item.meta}</Text></View><Text style={styles.status}>{item.status}</Text></View></View>)}<View style={styles.deadline}><View style={styles.deadlineIcon}><CheckCircle2 color={colors.lime} size={20} /></View><View><Text style={styles.deadlineTitle}>Deadline sắp tới</Text><Text style={styles.deadlineText}>Bài tập Hình học · còn 2 ngày</Text></View></View><Pressable accessibilityRole="button" onPress={() => navigation.navigate('OCR')} style={styles.fab}><ScanLine color={colors.ink} size={20} /><Text style={styles.fabText}>Quét bài tập</Text></Pressable></ScrollView>;
}

const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 22 }, greeting: { marginTop: 6, fontSize: 28 }, avatar: { backgroundColor: colors.coral, borderRadius: 20, color: colors.ink, fontSize: 18, fontWeight: '800', padding: 11 }, titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 30, marginBottom: 14 }, sectionTitle: { color: colors.ink, fontSize: 24, fontWeight: '800' }, event: { alignItems: 'center', flexDirection: 'row' }, time: { color: colors.muted, fontSize: 12, fontWeight: '800', width: 48 }, marker: { borderRadius: 4, height: 44, marginRight: 12, width: 5 }, eventCopy: { flex: 1 }, eventTitle: { color: colors.ink, fontSize: 15, fontWeight: '800', marginBottom: 4 }, status: { color: colors.muted, fontSize: 10, fontWeight: '700' }, deadline: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: 18, flexDirection: 'row', marginTop: 12, padding: 15 }, deadlineIcon: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: 12, height: 40, justifyContent: 'center', marginRight: 12, width: 40 }, deadlineTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, deadlineText: { color: colors.ink, fontSize: 11, marginTop: 3, opacity: .65 }, fab: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.lime, borderRadius: 99, flexDirection: 'row', marginTop: 22, paddingHorizontal: 17, paddingVertical: 13 }, fabText: { color: colors.ink, fontSize: 13, fontWeight: '800', marginLeft: 8 } });
